name: Assets

on:
  workflow_dispatch:

jobs:
  assets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - run: npm run build-assets

      - name: Verificar ficheiros gerados (Debug)
        run: ls -la dist-assets/

      - name: Upload assets
        env:
          GH_TOKEN: ${{ secrets.ASSETS_TOKEN }}
        run: |
          gh release upload assets \
            dist-assets/* \
            --repo boltnoak/boltnotes-assets \
            --clobber